### ISSUE TITLE
Link to flight framework site is broken

### ISSUE THREAD

**Issue by gianpaj** [bento-io/collection#103]
Even though the content.json is correct and the generated html too:

```
<a target="_blank" class="title ng-binding" name="flight" href="http:/flightjs.github.io">flight</a>
```

The browser thinks the url is "http://www.bentobox.io/flightjs.github.io"

broken in 
- Chromium 30
- Firefox 23

works in
- Safari 6.0.5

**Comment by JonHMChan** [comment]
Fixed! https://github.com/JonHMChan/bento/commit/1358e1d2c9e161632f68c05857a551fb20dbdc57

**Comment by gianpaj** [comment]
lol, not sure how i didn't catch that :)

strange that Safari "fixes" that though :P

**Comment by JonHMChan** [comment]
It happens to the best of us :)

On Sun, Oct 20, 2013 at 1:03 PM, Gianfranco Palumbo <
notifications@github.com> wrote:

> lol, not sure how i didn't catch that :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JonHMChan/bento/issues/103#issuecomment-26677186
> .

## 

Creator of Bento http://bentobox.io/ |
@jonhmchanhttp://twitter.com/jonhmchan| 626-628-5875
