### ISSUE TITLE
Break out first three rows as an "essential curriculum"

### ISSUE THREAD

**Issue by JonHMChan** [bento-io/collection#137]
The number of boxes that are on Bento is starting to get unwieldy. I've gotten numerous comments that the large list of technologies is overwhelming to a beginner. As a measure, I think that it makes sense to figure out which are the absolutely **essential** needs for a full-stack developer in the beginning stages (someone you would be willing to hire perhaps as an intern) and put the rest under a fold.

I think the first three rows are a pretty good start. It should cover:
- Web fundamentals (understanding what IP addresses are, http, etc.)
- Front-end basics (HTML, CSS, JavaScript)
- One strong backend language and framework (I prefer Python on Flask)
- A database / query language (I think SQL is best)
- Basic version control (Git)
- Basics on hosting and domains (needs to be filled, but Heroku is a good one)

**Comment by dfosco** [comment]
Hey Jon,

Have you considered hiding the "unused" boxes for better overview of the selected language and its related boxes? Perhaps reordering them to bring them closer together (as you seem to imply in this latest commit) might work as well.

I feel like Bento would benefit from _less_ discoverability, in the sense that it can provide a certain progressive disclosure — if I'm a total newbie that wants to start with HTML/CSS, there's really no need for me to see Rails right away.

**Comment by JonHMChan** [comment]
Yes, I do think that's what I'd like to have happen. I think that having the rest of the boxes after the essential ones as hidden would help.

I only have two reservations:
- There is a significant number of people who come to the site who are _not_ beginners. They come to the site with the hope that there are simple tutorials for advanced technologies, which are actually more obscure to find than the beginning ones. There is a sense in which that Bento serves two ends of the spectrum: (1) for the beginner, there's _too many_ resources to figure out which ones are meaningful, and (2) for the more advanced, where there are _too few_ resources at low quality to be helpful.
- I also do not want to give the impression that one implementation is "better" than another - I do think that there are certain technologies that are **easier to learn**. Putting these resources behind a fold may give the wrong impression, without a significant disclaimer.

Thoughts?

**Comment by dfosco** [comment]
Agreed! I think Bento could serve these two needs by adopting two models/forms of navigation:
- _I need to make a website/webapp/app_ — Similar to Treehouse tracks, these could aggregate the most basic languages and resources that a beginner could/should learn. Further resources could be suggested with less emphasis to fill the needs of intermediary users.
- _I want to get into Rails/MongoDB/java/whatever_ —This user could be shown more information, but I feel like a layout akin to an _index card_, with one main information highlighted and secondary content below, would be more useful. 
  
  Even an advanced user will hardly need to use Python & Rails & PHP & .net at the same time, so I'm not sure showing a lot of different stuff simultaneously brings an advantage for him.

Thoughts? I could make some wireframes to further clarify these ideas if you think it's worth a shot.

**Comment by JonHMChan** [comment]
This is satisfied and will be enhanced with Learning Tracks.
