### ISSUE TITLE
bug: facebook button overlaps twitter

### ISSUE THREAD

**Issue by gigerbytes** [bento-io/collection#159]
steps:
1. load home page fully
2. click the 'show more links' in a box
3. press back

Experienced in opera and chromium

the following happens
![screen shot 2014-04-01 at 9 43 54 pm](https://cloud.githubusercontent.com/assets/5770876/2579639/c050ebd4-b9a3-11e3-9c88-78d92e9a83fc.png)

**Comment by JonHMChan** [comment]
Pushed a fix
