### ISSUE TITLE
pseudo code

### ISSUE THREAD

**Issue by hannah123** [bento-io/collection#163]
Hello, 
i was wondering if you could create a box that showed the best sites to learn pseudo code? 

Thanks,
Hannah Mathews

**Comment by Nightfirecat** [comment]
Um, could you define "pseudo code" more? I'm not actually sure what you'd be interested in being available - it isn't actually a programming language.

**Comment by nhsz** [comment]
I think that pseudo-code isn't very related with web development properly, but with CS fundamentals, to start "thinking" that way. Check the "Think Python" book in the python section.
