### ISSUE TITLE
Change link hover colors

### ISSUE THREAD

**Issue by ivychen** [bento-io/collection#166]
I suggest changing the hover-over color of the links. The blocks that contain darker background colors don't contrast well with the blue hyperlinks. However, we all would be hard pressed to find a suitable color that contrasts against all backgrounds. That's why I thought of using something like this: http://jsfiddle.net/9Ljrf/1/ (a quick, messy mockup)
I haven't yet thought of what to do when you hover over, though.

**Comment by Nightfirecat** [comment]
I find it's not as much an issue for the hover as it is for visited links - they also have the same blue color.

It may be best to avoid using hover/visited styles entirely, or to use styles that don't revolve around changing the text color?

**Comment by JonHMChan** [comment]
Right now the only way to check if someone has already seen a resource is through that coloring - in the near future, user accounts should be able to keep track. A feature deferred for now.
