### ISSUE TITLE
Incorrect Categories

### ISSUE THREAD

**Issue by JaredCubilla** [bento-io/collection#180]
Grunt should be in the "foundational" category, backbone, ember, and coffeescript should be in "frontend".

**Comment by Psymen** [comment]
All valid points. @JonHMChan, just submitted a PR to address this.

**Comment by JonHMChan** [comment]
Merged.

**Comment by JaredCubilla** [comment]
After the merge, some weird things happened... Backbone, Ember and Coffeescript are present when I click on Frontend, but remain blue, indicating it as a backend. When I click on backend, those three appear again.

Also, Grunt is still in the backend.

**Comment by JonHMChan** [comment]
There was a recent change in the way that the data is handled on the backend. Basically, Bento is no longer pulling the JSON directly through github and is doing an import to translate it into a postgres db. As you can see, there are some kinks to still get worked out. Updates soon.

**Comment by JonHMChan** [comment]
Once the redis cache clears out in a few hours, this should be fixed.

**Comment by JaredCubilla** [comment]
Ah I see. Will you update the README with this information?

**Comment by JonHMChan** [comment]
It's a very recent change so yes - very soon—
