### ISSUE TITLE
Single word for profile name throws a "IndexError: list index out of range"

### ISSUE THREAD

**Issue by LeonTheGreat** [bento-io/collection#192]
I noticed that at https://www.bento.io/home when looking at my profile, when I tried changing my user name from my actual name to "lennys", which I normally use as a username, it threw a "IndexError
IndexError: list index out of range" error. I played with it a little and found that if I added an empty space after my "lennys" username, it would accept the change. So it looks like trying to use one word as your profile name causes an error.

**Comment by JonHMChan** [comment]
I've adjusted this to have the expected behavior. For now, Bento does require that you provide your real, full name - usernames may be something supported in the future. However, you shouldn't be seeing any errors one way or the other. Thanks for pointing this out!
