### ISSUE TITLE
Provide a way to dismiss the banner and/or search box

### ISSUE THREAD

**Issue by kmoe** [bento-io/collection#205]
The original bento.io website had a simple design that made good use of the space available. 
It would be good if we could dismiss the "learning tracks" banner and/or the search banner at the bottom in order to give as much space as possible to the content (the coloured boxes).

![image](https://cloud.githubusercontent.com/assets/5575356/4782089/dbba4228-5cda-11e4-9801-f6f7149db644.png)

**Comment by JonHMChan** [comment]
I'm thinking of putting in a vanishing top bar with scroll down - that might actually do it well.

**Comment by JonHMChan** [comment]
Take a look at it now - top bar now actually fades away on scroll down, appears on scroll up.
