### ISSUE TITLE
Can't Login/Register

### ISSUE THREAD

**Issue by Endermod** [bento-io/collection#207]
There is no place to login/register.
![capture](https://cloud.githubusercontent.com/assets/3856177/4912021/3a670afe-6497-11e4-9a5b-83a9468751bd.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3856177/4912022/3a6bf28a-6497-11e4-99a7-6922f4682f32.PNG)

**Comment by JonHMChan** [comment]
What browser and version are you using?

**Comment by Endermod** [comment]
Chrome, newest.

**Comment by JonHMChan** [comment]
Hm, I can't reproduce - is this happening in any other browser?

**Comment by ScottC95** [comment]
I was also having this problem on latest chrome, turned out adblock was blocking them. 
Hope this helps.

**Comment by JonHMChan** [comment]
Yes, it looks like AdBlock is actually causing this issue. I'll look into how this might be avoided.

**Comment by ScottC95** [comment]
That's great , glad I could be of help

**Comment by JonHMChan** [comment]
This should be resolved - can anyone confirm before I close?

**Comment by ScottC95** [comment]
It's working fine now with adblock enabled
