### ISSUE TITLE
Tone of opening tour

### ISSUE THREAD

**Issue by zarchive** [bento-io/collection#218]
I like sites like this and intend to use it, but the tone of "wow, great job reading a few lines and clicking a big blue button" feels ridiculous. I have no need to be immediately "reached out" to by everyone whose website I use either. It's nice and I intend to talk to people too, but can it be optional? It's all bizarrely condescending and in-your-face.

**Comment by JonHMChan** [comment]
The beginning onboarding is being revamped - agreed it needs to be revisited. Will address in a separate issue.
