### ISSUE TITLE
Suggestion: Remember me (login)

### ISSUE THREAD

**Issue by mobesa** [bento-io/collection#219]
Hi,
I've been frequently visiting Bento.io and logging in _every time_. Isn't there a _remember me_ function? That would be great and useful if there were one.

**Comment by JonHMChan** [comment]
Good question. Currently, it's not implemented because of the way that OAuth is done with Google and Facebook. This is a systemic issue and will look into it.

**Comment by mobesa** [comment]
Thanks @JonHMChan!

**Comment by JonHMChan** [comment]
This should be resolved. Try it out!
