### ISSUE TITLE
Adding deploy options

### ISSUE THREAD

**Issue by acmisiti** [bento-io/collection#221]
Have you considered creating another category that helps people learn how to deploy projects? Examples using saltstack, ansible, fabric, etc.

**Comment by JonHMChan** [comment]
The only blocker here is that we need good free tutorials that explain this information well. Heroku is a good example of a deployment solution that has a wealth of high-quality, freely accessible educational material that we can highlight. If you have suggestions for other deployment options that meet the requirements in the README, feel free to add it to `content.json`
