### ISSUE TITLE
Main page: 'Programming Methodology' link not available

### ISSUE THREAD

**Issue by RickyCh** [bento-io/collection#240]
1. Open Bento main page: https://www.bento.io/
2. Find 'java' block which is on the lower part of Bento's main page
3. Click 'Programming Methodology' link

OS: Ubuntu 14.04
Browser: Chrome 45.0.2454.85
Attached is the screenshot of this unavailable link.
![click bug with empty resource](https://cloud.githubusercontent.com/assets/14843212/10112343/4d1b66ac-638f-11e5-9de5-2b9db3678db9.png)

**Comment by Nightfirecat** [comment]
It looks like Stanford changed their course layout on their website; the new course appears to be available here: https://see.stanford.edu/Course/CS106A

**Comment by RickyCh** [comment]
Thanks for notifying!

**Comment by Nightfirecat** [comment]
Don't close this issue please &mdash; this link is still broken on the site, and should be changed to be correct for others.

**Comment by RickyCh** [comment]
Sorry, I'm new to use github. Thanks.

**Comment by JonHMChan** [comment]
Resolved with https://github.com/bento-io/collection/commit/ea3a19d689b2b2ea343b3a0f6d200889400f05ec
