### ISSUE TITLE
Basic Data Structures link

### ISSUE THREAD

**Issue by demidovakatya** [bento-io/collection#241]
http://interactivepython.org/runestone/static/pythonds/BasicDS/basic.html
↑ this is the current link and it is broken

↓ this link leads to the table of contents, 'Basic Data Structures' section
http://interactivepython.org/runestone/static/pythonds/index.html#basic-data-structures

**Comment by JonHMChan** [comment]
Thanks for catching, updated with https://github.com/bento-io/collection/commit/e2d4a50cc2b760d32b167c150693639e70c4abea
