### ISSUE TITLE
Database track has a non functioning link for the playlist

### ISSUE THREAD

**Issue by brianjpeter** [bento-io/collection#246]
https://www.bento.io/tracks/databases

Foundations
Foundations of Programming: Databases
Links to this playlist on Youtube: https://www.youtube.com/playlist?list=PLnxBrInqFEs7DqOUljmVlgZ_xRRSsyesu

But YouTube returns with "The playlist does not exist."

**Comment by JonHMChan** [comment]
Thanks for spotting that. Will resolve.

**Comment by JonHMChan** [comment]
Resolved. https://github.com/bento-io/collection/issues/257
