### ISSUE TITLE
Linkrot: Databases > Alembic > Basic Alembic Migrations with Flask

### ISSUE THREAD

**Issue by terepanda** [bento-io/collection#257]
Hi,
I found a dead link to "Basic Alembic Migrations with Flask" in the Databases (https://www.bento.io/tracks/databases).
"http://michaelmartinez.in/basic-alembic-migrations-with-flask.html" is not working.
"http://mmartinez.us/2013/05/basic-alembic-migrations-with-flask/" might be the new one.
Regards.

**Comment by JonHMChan** [comment]
Crap. Looking now.

**Comment by JonHMChan** [comment]
Been fixed. Replaced with another tutorial.
