### ISSUE TITLE
This link in database track doesnt work anymore

### ISSUE THREAD

**Issue by luong-komorebi** [bento-io/collection#272]
https://pythonhosted.org/Flask-SQLAlchemy/quickstart.html flasksql alchemy not working

**Comment by JonHMChan** [comment]
This should be resolved now to http://flask-sqlalchemy.pocoo.org/2.1/quickstart/ - can you confirm?

**Comment by luong-komorebi** [comment]
@JonHMChan Thank you. It's working nice now
