### ISSUE TITLE
Project/technology names should be capitalized correctly

### ISSUE THREAD

**Issue by geary** [bento-io/collection#32]
Don't force names like HTML, CSS, JavaScript, jQuery, and Python to lowercase. Use the correct capitalization of each name.

Remember that we are programmers who work in mostly case-sensitive languages, so even if you like to force names to lowercase for stylistic reasons, it looks too much like a syntax error.

**Comment by Eponymi** [comment]
+1, unfortunately so much of this is focused on its appearance instead of it's stated mission of helping beginners (or actually working, for that matter), I doubt that the maintainer is going to worry about presenting technology names in their proper form.

**Comment by JonHMChan** [comment]
I agree with you - the names just need to parsed so they match each following lesson afterwards. Will put this in a coming update or PR
