### ISSUE TITLE
Virtual Machines

### ISSUE THREAD

**Issue by Eponymi** [bento-io/collection#37]
As someone who has gone from not knowing what the letters in HTML stand for to a salaried developer in ~2 years using nothing but online resources, I can state without hesitation that my biggest advancement was learning about virtualization and the idea of environments about 6 months ago. Up until that point, it was all MAMP, and I never saw the purpose of using anything else.

I'm biased towards vagrant, because it's what I use everyday. But offering up any virtualization tool(s) would save the savvy beginner a lot of future headaches, and give them a truly marketable skill. 

Virtualization is the first topic I cover with junior devs, and is essential  if we're talking about "building" things. If you can mock your environment (or better yet, environments), setting up and maintaining servers---the foundation of actually shipping to the web---is a piece of cake.

**Comment by emirozer** [comment]
+1 good point + maybe mention docker.io too as its the newest way and its popularity is ramping up

**Comment by JonHMChan** [comment]
Docker certainly is a good one I'll add that in! There is a vm there (vagrant?) - quite honestly I don't know too much about it. If anyone can put in a PR with suggestions in content.json that'd be great! Otherwise, I'll add it in

**Comment by ghost** [comment]
I'd say to add a section on Vagrant, a section on Virtualbox, and a section on Docker. 

So it'd go Virtualbox -> Vagrant -> Docker

But before Vagrant, you need something on Puppet/Chef in order to get the most out of it.

**Comment by JonHMChan** [comment]
Any suggestions for links? Not an expert here on VM!

**Comment by ghost** [comment]
Hmmm. There's just a lot of topics to cover within virtualization. It might help to keep things organized if larger categories were added (like languages, services, etc), especially as the number of topics listed grows pretty quickly. For now, I'd say just add Virtualbox, as there are too many interconnected things to do it well without categories

**Comment by dylanlgs** [comment]
I would argue that VM/vagrant on its own is a valuable enough without config management. To truly leverage config management, you need to be familiar with a ton of software. To leverage virtualization, you just need to understand the _concept_ of mocking environments.

**Comment by JonHMChan** [comment]
We've added a few in here.
