### ISSUE TITLE
Unstable colors

### ISSUE THREAD

**Issue by emirozer** [bento-io/collection#44]
Hi John,

On chrome if you click a resource header (like css xml etc) and go back to bento , colors become unstable like this : 
![bentobug](https://f.cloud.github.com/assets/5015104/1186139/e9015818-22e3-11e3-8be7-b6a6bce1244b.png)

**Comment by JonHMChan** [comment]
That's actually meant to happen. If a user clicks on a link in one of the boxes, it highlights the next lessons and grays everything else out.

**Comment by emirozer** [comment]
oh okay , i tought you meant to gray out the ones we stopped by. my bad than :)

**Comment by JonHMChan** [comment]
No problem! I think I should do something about the links that people have visited though, that's not a bad suggestion :)
