### ISSUE TITLE
APIs

### ISSUE THREAD

**Issue by carloskcheung** [bento-io/collection#50]
Do you know of any good resources to learn about APIs from bottom-up? 

-CC

**Comment by JonHMChan** [comment]
Yes! Are you talking about APIs generally or a collection of them? I'm planning on adding boxes for each major api

**Comment by carloskcheung** [comment]
I think adding a box for each major API is great, but APIs generally is great is well. Trying to prepare myself for the API conference in SF. I have a slight knowledge of what API is, but not sure where to go to learn more.

**Comment by JonHMChan** [comment]
I've added a general api one (though about designing APIs rather than using on) - I've also added some of the common ones

**Comment by JonHMChan** [comment]
Also, Mashape was added in there as well - I think we're covered here for the basics!

**Comment by carloskcheung** [comment]
Thanks Jon!
