### ISSUE TITLE
Readme lacks instructions for running locally

### ISSUE THREAD

**Issue by colemanfoley** [bento-io/collection#63]
I'm trying to figure out how to run it locally to try out some changes, and am finding it not very obvious. Instructions could save contributors some time.

**Comment by JonHMChan** [comment]
What kind if changes are you trying to make here? If it's just to make a change to a link, that should be done directly on content.json

If you're looking to do something beyond that, you can also test on your own machine just by firing index.html in Firefox (chrome doesn't allow for local JSON loads). It won't have the type kit enabled, but it should give you a good idea of what's going on.

—

**Comment by colemanfoley** [comment]
Yeah, I wanted to mess around with the layout, not just the JSON file. I was trying to open index.html in Chrome, so the Firefox tip is what I needed. Thanks.

I think quite a few people will try to open it locally, on Chrome, so it could be helpful to have that tip in the Readme.

**Comment by JonHMChan** [comment]
I'll add that in - thanks! I also advise that you make another pull in if
that's the case. There have been a few structural changes have just been
pushed.

**Comment by colemanfoley** [comment]
Ok, thanks, Jon.

**Comment by JonHMChan** [comment]
Sure thing! thanks so much for contributing here
