### ISSUE TITLE
Foursquare, Facebook

### ISSUE THREAD

**Issue by dmfilipenko** [bento-io/collection#69]
Hi JonHMChan and all contributors of this resource. I really like it.
And i have one questions. You show at one level PHP, Ruby, Javascript, etc. and Facebook with Foursquare which aren't programming language. Maybe it's better to change it location, put it on another logical level or create for this purpose some category? What do you think about it?

**Comment by JonHMChan** [comment]
it's less clear that these are APIs that are being referred to. You're right though, should be in a different area. I think I just need to take some time rearrange things on the grid.

**Comment by JonHMChan** [comment]
Rearranged recently.
