### ISSUE TITLE
Some links do not make sense

### ISSUE THREAD

**Issue by DmitryEfimenko** [bento-io/collection#80]
Why clicking on "sql" highlights "json"? These two technologies are not really connected. Json would be more relevant for "nosql"

Why clicking on "sql" does not highlight "postgresql"

Why when clicking on "html", "php" is highlighted, but none of the other server side technologies like "python", "ruby", ".net"...?

**Comment by JonHMChan** [comment]
I haven't been able to parse through each of the boxes to see where they should connect - only the top ones have been somewhat vetted. You can change what you think the next highlighted boxes should be by changing the parameters in $then for each of the nodes in content.json

**Comment by DmitryEfimenko** [comment]
I didn't want to do the changes before discussing them with you for the things that were not clear to me.
I'll go ahead and update links then.

**Comment by JonHMChan** [comment]
Meaningfully vetted recently.
